# Generated by Django 4.0.6 on 2022-07-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег мазагина',
                'verbose_name_plural': 'Теги мазагинов',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название магазина')),
                ('description', models.TextField(default='', verbose_name='Описание магазина')),
                ('phone', models.CharField(max_length=15, verbose_name='Основной номер')),
                ('logo', models.FileField(upload_to='shops/logotypes/')),
                ('is_verify', models.BooleanField(default=False, verbose_name='Статус верификации')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность магазина')),
                ('tags', models.ManyToManyField(blank=True, to='shops.markettag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
    ]
