# Generated by Django 4.0.6 on 2022-07-24 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_marketitem_market_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitem',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.market'),
        ),
    ]
