version: "3"

services:
  postgresql:
    image: postgres:12
#    restart: always # prod mode
    volumes:
      - ./.data/postgres-data:/var/lib/postgresql/data
    env_file:
      - ./services/postgresql/.env

  redis:
    image: redis
#    restart: always # prod mode

  nginx:
    image: nginx
#    restart: always # prod mode
    depends_on:
      - backend
    ports:
      - "8899:80"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.data/static-django:/static-django
      - ./.data/media-django:/media-django

  backend:
    build:
      context: ../backend
#    restart: always # prod mode
#    command: daphne -b 0.0.0.0 -p 8000 src.asgi:application
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../backend:/code # develop mode
      - ./.data/static-django:/static
      - ./.data/media-django:/media
    env_file:
      - ./apps/backend/.env
      - ./services/postgresql/.env
    depends_on:
      - postgresql
