# Generated by Django 4.0.6 on 2022-07-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide',
            field=models.BooleanField(default=True, verbose_name='Статус скрытности'),
        ),
    ]
